#pragma once
#define RGB_DISABLE_WHEN_SUSPENDED true
#define TAPPING_TERM 200
#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_DELAY 0
#define MOUSEKEY_TIME_TO_MAX 45
#define MOUSEKEY_MAX_SPEED 9
#define MOUSEKEY_WHEEL_DELAY 0
