//  Define custom keycodes to better fit grid
#define L_SHIFT OSM(MOD_LSFT)
#define CTL_TAB LCTL(KC_TAB)
#define LT4_GRV LT(_L4, KC_GRV)
#define LT_3SPC LT(_L3, KC_SPC)
#define LT_5ESC LT(_L5, KC_ESC)
#define GUI_SPC LGUI(KC_SPC)
#define SFT_SPC SFT_T(KC_SPC)
#define SL3_ENT LT(_SL3, KC_ENT)
#define LT_2QUO LT(_L3, KC_QUOT)
#define WKSPC_L LCTL(KC_LEFT)
#define WKSPC_R LCTL(KC_RIGHT)
#define WKSPC_D LCTL(KC_DOWN)
#define WKSPC_U LCTL(KC_UP)
#define LT_TAB  LT(_L3, KC_TAB)
#define TD_LSFT TD(FB_TD_SFT)
#define TD_MINS TD(FB_TD_MIN)
#define KC_PATH LGUI(LSFT(KC_G))
#define KC_ZUMI LGUI(KC_EQL)
#define KC_ZUMO LGUI(KC_MINS)
#define FB_COMM FB_COMMENT
#define FB_COM TD(FB_TD_COM)
#define FB_WEBB LGUI(KC_LBRC)
#define FB_WEBF LGUI(KC_RBRC)
#define FB_PARE TD(FB_TD_PAR)
#define FB_BRK TD(FB_TD_BRK)
#define FB_9P TD(FB_TD_9P)
#define FB_0P TD(FB_TD_0P)
#define LT2_SPC LT(_L2, KC_SPC)
#define LT3_SPC LT(_L3, KC_SPC)
#define FB_DH TD(FB_TD_DH)
#define FB_UE TD(FB_TD_UE)
#define FB_BBAK LALT(KC_BSPC)
#define LT3_MIN LT(_L3, KC_MINS)
#define TO_L5 TO(L5)
#define TO_L1 TO(L1)
#define WIN_LH LCTL(LALT(KC_LEFT))
#define WIN_RH LCTL(LALT(KC_RIGHT))
#define WIN_TL LCTL(LALT(KC_U))
#define WIN_TR LCTL(LALT(KC_I))
#define WIN_BL LCTL(LALT(KC_J))
#define WIN_BR LCTL(LALT(KC_K))
#define WIN_MX LCTL(LALT(KC_ENT))
#define KC0_FLY LT(_L6, KC_0)
